### ISSUE TITLE
Yocto firmware generation error (ceph)

### ISSUE THREAD

**Issue by AncientByte** [seapath/yocto-bsp#36] opened 2024-03-18 13:49 UTC
While generating the firmware with cqfd the following errors always occur:

![FirmwareGenerationError](https://github.com/seapath/yocto-bsp/assets/34119969/46652015-c74f-4873-b8c2-ad974edbd8a0)

I followed the steps of the documentation for preparing and generating the firmware. After using the  `cqfd -b host_efi_test` command in the terminal the firmware generation is started. After some time the error messages shown above occur in the terminal. The same thing happend with other cqfd flavors like `host_efi`. 

I expected the generation to run further and as a result getting the desired firmware.

I tried the firmware generation on a virtual machine with the following specifications:
Ubuntu 22.04.4 Desktop amd64
8 GB RAM
4 Cores of the i7-4790S
400 GB storage space

The error occured also on the following system:
Intel NUC 12
Ubuntu 18
i7-1260P
64 GB DDR4 RAM
2 TB M.2 SSD

This is a screenshot of the corresponding log file:

![LogFirmwareGenerationError](https://github.com/seapath/yocto-bsp/assets/34119969/e1b6942d-2733-49ee-b5d9-1b22652a17af)

**Comment by eroussy** [comment] 2024-07-18 09:30
Hi.
Sorry for missing this issue.
It seems it was a problem of ceph compilation at the time on the meta-virtualization.
I compiled ceph on a fresh installation today and the problem is gone.

I closed this as not applicable anymore, feel free to reopen if needed.

**Closed as completed by eroussy** 2024-07-18 09:30 UTC
Labels: bug
